server:
  port: 7879
  tomcat:
    max-swallow-size:
spring:
  mvc:
    static-path-pattern: D:/upload/**
  servlet:
    multipart:
      enabled: true
      max-file-size: 10GB
      max-request-size: 10GB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/video?useUnicode=true&characterEncoding=utf-8
    username: root
    password: wangfei
    #url:  jdbc:mysql://35.80.126.45:3306/video?useUnicode=true&characterEncoding=utf-8
    #username: yiben
    #password: yiben123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
knife4j:
  production: false
  # 配置自定义markdown文件的位置
  # markdowns: classpath:markdown/*

swagger:
    production=true
debug: false
file:
  path: file/**    #文件访问路径
  address:  D:/videos/  #文件保存路径
#文件上传目录（注意Linux和Windows上的目录结构不同）
#uploadFolder=/root/upload/
#特别要注意此位置
#uploadFolder=D:/upload/
#本地文件
url: http://192.168.31.117:7879/file/