server:
  port: 7879
  tomcat:
    max-swallow-size:
spring:
  datasource:
    url:  jdbc:mysql://35.80.126.45:3306/video?useUnicode=true&characterEncoding=utf-8
    username: yiben
    password: yiben123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
knife4j:
  production: false
  # 配置自定义markdown文件的位置
  # markdowns: classpath:markdown/*

swagger:
    production=true
debug: false